OLD_SHOWS = [
  {
    venue: "Short Branch Saloon",
    city: "Neenah, WI",
    date: new Date("2017/02/04"),
    imageSrc: "./img/shows/shortbranch.jpg",
    imageAlt: "Short Branch Saloon",
    description: "Playing with Unity the Band",
  },
  {
    venue: "Pops Blue Moon",
    city: "St. Louis, MO",
    date: new Date("2017/02/06"),
    imageSrc: "./img/shows/popsblue.gif",
    imageAlt: "Pops Blue Moon",
    description: "Playing with Corn Fed Still",
  },
  {
    venue: "Barley's Taproom",
    city: "Knoxville, TN",
    date: new Date("2017/02/07"),
    imageSrc: "./img/shows/barleys.png",
    imageAlt: "Barley's Taproom",
  },
  {
    venue: "Springwater Supper Club",
    city: "Nashville, TN",
    date: new Date("2017/02/08"),
    imageSrc: "./img/shows/springwater-supperclub.png",
    imageAlt: "Springwater Supper Club",
    description: "Playing with Fumblebuckers and Tyler David"
  },
  {
    venue: "Stanley's Pub",
    city: "Cincinnati, OH",
    date: new Date("2017/02/09"),
    imageSrc: "./img/shows/stanleys.jpg",
    imageAlt: "Stanley's Pub",
    description: "With special guest Willow Tree Carolers",
  },
  {
    venue: "Red Herring Lounge",
    city: "Duluth",
    date: new Date("2017/02/17"),
    imageSrc: "./img/shows/red-herring.png",
    imageAlt: "Red Herring Lounge",
    description: "Playing with Kind Country",
  },
  {
    venue: "Dempsey's Public House",
    city: "Fargo, ND",
    date: new Date("2017/02/18"),
    imageSrc: "./img/shows/dempseys.png",
    imageAlt: "Dempsey's Public House",
    description: "Playing with Kind Country",        
  },
  {
    venue: "Icehouse",
    city: "Minneapolis",
    date: new Date("2017/02/23"),
    imageSrc: "./img/shows/icehouse.png",
    imageAlt: "Icehouse",
  },
  {
    venue: "What's Up Lounge",
    city: "Mankato, MN",
    date: new Date("2017/02/24"),
    imageSrc: "./img/shows/whatsup.png",
    imageAlt: "What's Up Lounge",
  },
  {
    venue: "Great Northern Bar",
    city: "Whitefish, MT",
    date: new Date("2017/03/10"),
    imageSrc: "./img/shows/greatnorthern.jpg",
    imageAlt: "Great Northern Bar",
    description: "Playing with Moonshine Mountain",        
  },
  {
    venue: "Stonefly Lounge",
    city: "Coram, MT",
    date: new Date("2017/03/11"),
    imageSrc: "./img/shows/stonefly.gif",
    imageAlt: "Stonefly Lounge",
    description: "Playing with Moonshine Mountain",        
  },
  {
    venue: "Zebra Lounge",
    city: "Bozeman, MT",
    date: new Date("2017/03/15"),
    imageSrc: "./img/shows/zebra.jpg",
    imageAlt: "Zebra Lounge",
  },
  {
    venue: "Dempsey's Public House",
    city: "Fargo, ND",
    date: new Date("2017/03/17"),
    imageSrc: "./img/shows/dempseys.png",
    imageAlt: "Dempsey's Public House",
    description: "St. Patrick's Day party!",
  },
  {
    venue: "Amsterdam Bar and Hall",
    city: "St. Paul",
    date: new Date("2017/03/18"),
    imageSrc: "./img/shows/amsterdam-bar.png",
    imageAlt: "Amsterdam Bar and Hall",
  },
  {
    venue: "Minocqua Brewery",
    city: "Minocqua, WI",
    date: new Date("2017/03/24"),
    imageSrc: "./img/shows/minocqua.png",
    imageAlt: "Minocqua Brewery",
  },
  {
    venue: "Orpheum Theatre",
    city: "Hancock, MI",
    date: new Date("2017/03/25"),
    imageSrc: "./img/shows/orpheum-hancock.jpg",
    imageAlt: "Orpheum Theatre",
  },
  {
    venue: "Des Moines Social Club",
    city: "Des Moines, IA",
    date: new Date("2017/04/07"),
    imageSrc: "./img/shows/desmoines-social.png",
    imageAlt: "Des Moines Social Club",
    description: "Playing with Good Morning Bedlam",
  },
  {
    venue: "Mountain Meltdown Festival",
    city: "Lutsen, MN",
    date: new Date("2017/04/08"),
    imageSrc: "./img/shows/mt-meltdown.jpg",
    imageAlt: "Mountain Meltdown",
    description: 'Here\'s a little preview for ya:<br> <iframe width="280" height="158" src="https://www.youtube.com/embed/7FhokGO1gj8" frameborder="0" allowfullscreen></iframe>  ',
  },
  {
    venue: "Red Herring Lounge",
    city: "Duluth",
    date: new Date("2017/04/12"),
    imageSrc: "./img/shows/red-herring.png",
    imageAlt: "Red Herring Lounge",
    description: "Playing with Cascade Crescendo",
  },
  {
    venue: "Gunflint Tavern",
    city: "Grand Marais, MN",
    date: new Date("2017/04/14"),
    imageSrc: "./img/shows/gunflint.jpg",
    imageAlt: "Gunflint Tavern",
  },
  {
    venue: "Gunflint Tavern",
    city: "Grand Marais, MN",
    date: new Date("2017/04/15"),
    imageSrc: "./img/shows/gunflint.jpg",
    imageAlt: "Gunflint Tavern",
  },
  {
    venue: "The Hook and Ladder Theater",
    city: "Minneapolis",
    date: new Date("2017/04/19"),
    imageSrc: "./img/shows/hook-and-ladder.png",
    imageAlt: "The Hook and Ladder Theater",
    description: "Playing with the Wooks!",
  },
  {
    venue: "Fernson Brew House",
    city: "Sioux Falls, SD",
    date: new Date("2017/04/22"),
    imageSrc: "./img/shows/fernson.jpeg",
    imageAlt: "Fernsen Brew House",
    description: "Playing with special guest Condor",
  },
  {
    venue: "Kind Country EP Release @ The Turf Club",
    city: "St. Paul",
    date: new Date("2017/05/13"),
    imageSrc: "./img/shows/turf.png",
    imageAlt: "Turf Club",
    description: "Tickets! Tickets! <a href='http://turfclub.net/show/2017-05-kind-country/'>Get some ticketst!</a>",
  },
  {
    venue: "Revival Music Festival 2017",
    city: "Geneva, MN",
    date: new Date("2017/05/26"),
    endDate: new Date("2017/05/28"),
    imageSrc: "./img/shows/revival-2017.png",
    imageAlt: "Revival Music Festival 2017",
    description: "Join us at the Harmony Park music garden in Geneva, MN for Revival 2017! <br>"+
      "<a href='http://revivalfestmn.com'>Grab yer tickets here.</a>",
  },
  {
    venue: "MN Bluegrass & Old Time Music Festival",
    city: "Richmond, MN",
    date: new Date("2017/06/03"),
    imageSrc: "./img/shows/mbotm.jpg",
    imageAlt: "MN Bluegrass & Old Time Music Festival",
    description: "Join us for the kickoff to the Minnesota Bluegrass and Old Time Music Association's festival",
  },
  {
    venue: "Loring Park Music Festival",
    city: "Minneapolis",
    date: new Date("2017/06/10"),
    imageSrc: "./img/shows/loring.jpg",
    imageAlt: "Loring Park Music Festival",
  },
  {
    venue: "The Potter's Shed",
    city: "Shell Lake, WI",
    date: new Date("2017/06/16"),
    imageSrc: "./img/shows/potters-shed.jpg",
    imageAlt: "The Potter's Shed",
  },
  {
    venue: "Mankato Solstice Music Festival",
    city: "Mankato",
    date: new Date("2017/06/24"),
    imageSrc: "./img/shows/mankato-solstice.jpg",
    imageAlt: "Mankato Solstice Music Festival",
    description: "Check out the <a href='http://www.mankatosolstice.com'>Mankato Solstice site</a> for more info!",
  },
  {
    venue: "Great Northern Bar",
    city: "Whitefish, MT",
    date: new Date("2017/07/06"),
    imageSrc: "./img/shows/greatnorthern.jpg",
    imageAlt: "Great Northern Bar",
  },      
  {
    venue: "Sandpoint Summerfest",
    city: "Sagle, ID",
    date: new Date("2017/07/07"),
    imageSrc: "./img/shows/sandpoint.jpg",
    imageAlt: "Sandpoint Summerfest",
  },
  {
    venue: "HIFI Music Hall",
    city: "Eugene, OR",
    date: new Date("2017/07/08"),
    imageSrc: "./img/shows/hifi-eugene.jpg",
    imageAlt: "HIFI Music Hall",
    description: "NW Strings Summit pre-party with Cascade Crescendo!"
  },
]