OLD_SHOWS = [
  {
    venue: "Short Branch Saloon",
    city: "Neenah, WI",
    date: new Date("2017/02/04"),
    imageSrc: "./img/shows/shortbranch.jpg",
    imageAlt: "Short Branch Saloon",
    description: "Playing with Unity the Band",
  },
  {
    venue: "Pops Blue Moon",
    city: "St. Louis, MO",
    date: new Date("2017/02/06"),
    imageSrc: "./img/shows/popsblue.gif",
    imageAlt: "Pops Blue Moon",
    description: "Playing with Corn Fed Still",
  },
  {
    venue: "Barley's Taproom",
    city: "Knoxville, TN",
    date: new Date("2017/02/07"),
    imageSrc: "./img/shows/barleys.png",
    imageAlt: "Barley's Taproom",
  },
  {
    venue: "Springwater Supper Club",
    city: "Nashville, TN",
    date: new Date("2017/02/08"),
    imageSrc: "./img/shows/springwater-supperclub.png",
    imageAlt: "Springwater Supper Club",
    description: "Playing with Fumblebuckers and Tyler David"
  },
  {
    venue: "Stanley's Pub",
    city: "Cincinnati, OH",
    date: new Date("2017/02/09"),
    imageSrc: "./img/shows/stanleys.jpg",
    imageAlt: "Stanley's Pub",
    description: "With special guest Willow Tree Carolers",
  },
  {
    venue: "Red Herring Lounge",
    city: "Duluth",
    date: new Date("2017/02/17"),
    imageSrc: "./img/shows/red-herring.png",
    imageAlt: "Red Herring Lounge",
    description: "Playing with Kind Country",
  },
  {
    venue: "Dempsey's Public House",
    city: "Fargo, ND",
    date: new Date("2017/02/18"),
    imageSrc: "./img/shows/dempseys.png",
    imageAlt: "Dempsey's Public House",
    description: "Playing with Kind Country",        
  },
  {
    venue: "Icehouse",
    city: "Minneapolis",
    date: new Date("2017/02/23"),
    imageSrc: "./img/shows/icehouse.png",
    imageAlt: "Icehouse",
  },
  {
    venue: "What's Up Lounge",
    city: "Mankato, MN",
    date: new Date("2017/02/24"),
    imageSrc: "./img/shows/whatsup.png",
    imageAlt: "What's Up Lounge",
  },
  {
    venue: "Great Northern Bar",
    city: "Whitefish, MT",
    date: new Date("2017/03/10"),
    imageSrc: "./img/shows/greatnorthern.jpg",
    imageAlt: "Great Northern Bar",
    description: "Playing with Moonshine Mountain",        
  },
  {
    venue: "Stonefly Lounge",
    city: "Coram, MT",
    date: new Date("2017/03/11"),
    imageSrc: "./img/shows/stonefly.gif",
    imageAlt: "Stonefly Lounge",
    description: "Playing with Moonshine Mountain",        
  },
  {
    venue: "Zebra Lounge",
    city: "Bozeman, MT",
    date: new Date("2017/03/15"),
    imageSrc: "./img/shows/zebra.jpg",
    imageAlt: "Zebra Lounge",
  },
  {
    venue: "Dempsey's Public House",
    city: "Fargo, ND",
    date: new Date("2017/03/17"),
    imageSrc: "./img/shows/dempseys.png",
    imageAlt: "Dempsey's Public House",
    description: "St. Patrick's Day party!",
  },
  {
    venue: "Amsterdam Bar and Hall",
    city: "St. Paul",
    date: new Date("2017/03/18"),
    imageSrc: "./img/shows/amsterdam-bar.png",
    imageAlt: "Amsterdam Bar and Hall",
  },
  {
    venue: "Minocqua Brewery",
    city: "Minocqua, WI",
    date: new Date("2017/03/24"),
    imageSrc: "./img/shows/minocqua.png",
    imageAlt: "Minocqua Brewery",
  },
  {
    venue: "Orpheum Theatre",
    city: "Hancock, MI",
    date: new Date("2017/03/25"),
    imageSrc: "./img/shows/orpheum-hancock.jpg",
    imageAlt: "Orpheum Theatre",
  },
  {
    venue: "Des Moines Social Club",
    city: "Des Moines, IA",
    date: new Date("2017/04/07"),
    imageSrc: "./img/shows/desmoines-social.png",
    imageAlt: "Des Moines Social Club",
    description: "Playing with Good Morning Bedlam",
  },
  {
    venue: "Mountain Meltdown Festival",
    city: "Lutsen, MN",
    date: new Date("2017/04/08"),
    imageSrc: "./img/shows/mt-meltdown.jpg",
    imageAlt: "Mountain Meltdown",
    description: 'Here\'s a little preview for ya:<br> <iframe width="280" height="158" src="https://www.youtube.com/embed/7FhokGO1gj8" frameborder="0" allowfullscreen></iframe>  ',
  },
  {
    venue: "Red Herring Lounge",
    city: "Duluth",
    date: new Date("2017/04/12"),
    imageSrc: "./img/shows/red-herring.png",
    imageAlt: "Red Herring Lounge",
    description: "Playing with Cascade Crescendo",
  },
  {
    venue: "Gunflint Tavern",
    city: "Grand Marais, MN",
    date: new Date("2017/04/14"),
    imageSrc: "./img/shows/gunflint.jpg",
    imageAlt: "Gunflint Tavern",
  },
  {
    venue: "Gunflint Tavern",
    city: "Grand Marais, MN",
    date: new Date("2017/04/15"),
    imageSrc: "./img/shows/gunflint.jpg",
    imageAlt: "Gunflint Tavern",
  },
  {
    venue: "The Hook and Ladder Theater",
    city: "Minneapolis",
    date: new Date("2017/04/19"),
    imageSrc: "./img/shows/hook-and-ladder.png",
    imageAlt: "The Hook and Ladder Theater",
    description: "Playing with the Wooks!",
  },
  {
    venue: "Fernson Brew House",
    city: "Sioux Falls, SD",
    date: new Date("2017/04/22"),
    imageSrc: "./img/shows/fernson.jpeg",
    imageAlt: "Fernsen Brew House",
    description: "Playing with special guest Condor",
  },
  {
    venue: "Kind Country EP Release @ The Turf Club",
    city: "St. Paul",
    date: new Date("2017/05/13"),
    imageSrc: "./img/shows/turf.png",
    imageAlt: "Turf Club",
    description: "Tickets! Tickets! <a href='http://turfclub.net/show/2017-05-kind-country/'>Get some ticketst!</a>",
  },
  {
    venue: "Revival Music Festival 2017",
    city: "Geneva, MN",
    date: new Date("2017/05/26"),
    endDate: new Date("2017/05/28"),
    imageSrc: "./img/shows/revival-2017.png",
    imageAlt: "Revival Music Festival 2017",
    description: "Join us at the Harmony Park music garden in Geneva, MN for Revival 2017! <br>"+
      "<a href='http://revivalfestmn.com'>Grab yer tickets here.</a>",
  },
  {
    venue: "MN Bluegrass & Old Time Music Festival",
    city: "Richmond, MN",
    date: new Date("2017/06/03"),
    imageSrc: "./img/shows/mbotm.jpg",
    imageAlt: "MN Bluegrass & Old Time Music Festival",
    description: "Join us for the kickoff to the Minnesota Bluegrass and Old Time Music Association's festival",
  },
  {
    venue: "Loring Park Music Festival",
    city: "Minneapolis",
    date: new Date("2017/06/10"),
    imageSrc: "./img/shows/loring.jpg",
    imageAlt: "Loring Park Music Festival",
  },
  {
    venue: "The Potter's Shed",
    city: "Shell Lake, WI",
    date: new Date("2017/06/16"),
    imageSrc: "./img/shows/potters-shed.jpg",
    imageAlt: "The Potter's Shed",
  },
  {
    venue: "Mankato Solstice Music Festival",
    city: "Mankato",
    date: new Date("2017/06/24"),
    imageSrc: "./img/shows/mankato-solstice.jpg",
    imageAlt: "Mankato Solstice Music Festival",
    description: "Check out the <a href='http://www.mankatosolstice.com'>Mankato Solstice site</a> for more info!",
  },
  {
    venue: "Great Northern Bar",
    city: "Whitefish, MT",
    date: new Date("2017/07/06"),
    imageSrc: "./img/shows/greatnorthern.jpg",
    imageAlt: "Great Northern Bar",
  },      
  {
    venue: "Sandpoint Summerfest",
    city: "Sagle, ID",
    date: new Date("2017/07/07"),
    imageSrc: "./img/shows/sandpoint.jpg",
    imageAlt: "Sandpoint Summerfest",
  },
  {
    venue: "HIFI Music Hall",
    city: "Eugene, OR",
    date: new Date("2017/07/08"),
    imageSrc: "./img/shows/hifi-eugene.jpg",
    imageAlt: "HIFI Music Hall",
    description: "NW Strings Summit pre-party with Cascade Crescendo!"
  },
  {
    venue: "NW String Summit",
    city: "North Plains, OR",
    date: new Date("2017/07/13"),
    endDate: new Date("2017/07/16"),
    imageSrc: "./img/nw-strings-summit.png",
    imageAlt: "NW String Summit",
  },
  {
    venue: "Craggy Range",
    city: "Whitefish, MT",
    date: new Date("2017/07/18"),
    imageSrc: "./img/shows/craggy-range.png",
    imageAlt: "Craggy Range",
  },      {
    venue: "Murray Bar",
    city: "Livingston, MT",
    date: new Date("2017/07/19"),
    imageSrc: "./img/shows/murray.jpg",
    imageAlt: "Murray Bar",
  },
  {
    venue: "Zebra Lounge",
    city: "Bozeman, MT",
    date: new Date("2017/07/20"),
    imageSrc: "./img/shows/zebra.jpg",
    imageAlt: "Zebra Lounge",
  },
  {
    venue: "Dempsey's Public House",
    city: "Fargo, ND",
    date: new Date("2017/07/21"),
    imageSrc: "./img/shows/dempseys.png",
    imageAlt: "Dempsey's Public House",
  },
  {
    venue: "Roots Revival Festival",
    city: "Algoma, WI",
    date: new Date("2017/07/22"),
    imageSrc: "./img/shows/roots-revival.png",
    imageAlt: "Roots Revival Festival",
  },
  {
    venue: "Galactic Get Down",
    city: "Lanesboro, MN",
    date: new Date("2017/07/29"),
    imageSrc: "./img/shows/galactic-get-down.jpg",
    imageAlt: "Galactic Get Down",
    description: "<a href='https://www.eventbrite.com/e/the-galactic-get-down-2017-tickets-31620491742'>Tickets here!</a>",
  },
  {
    venue: "Des Moines Social Club",
    city: "Des Moines, IA",
    date: new Date("2017/08/04"),
    imageSrc: "./img/shows/desmoines-social.png",
    imageAlt: "Des Moines Social Club",
    // description: "Pl aying with Good Morning Bedlam",
  },
  {
    venue: "Sioux River Folk Fest",
    city: "Newton Hills State Park, SD",
    date: new Date("2017/08/05"),
    imageSrc: "./img/shows/sioux-folk-fest.jpeg",
    imageAlt: "Sioux River Folk Fest",
    description: "",
  },
  {
    venue: "Zebra Lounge",
    city: "Bozeman, MT",
    date: new Date("2017/08/24"),
    imageSrc: "./img/shows/zebra.jpg",
    imageAlt: "Zebra Lounge",
  },
  {
    venue: "Broken Spoke",
    city: "Big Sky, MT",
    date: new Date("2017/08/25"),
    imageSrc: "./img/shows/brokenspoke.jpg",
    imageAlt: "Broken Spoke",
  },
  {
    venue: "The Deadication Festival",
    city: "Columbia Falls, MT",
    date: new Date("2017/08/26"),
    imageSrc: "./img/shows/deadication-fest.jpeg",
    imageAlt: "The Deadication Festival",
    description: "Come join us at Marantette Park in Columbia Falls, Montana!",
  },
  {
    venue: "Trout and About Festival",
    city: "Sandpoint, ID",
    date: new Date("2017/08/27"),
    imageSrc: "./img/shows/trout-and-about.jpg",
    imageAlt: "Trout and About Festival",
    // description: "Come join us at Marantette Park in Columbia Falls, Montana!",
  },
  {
    venue: "Gentleman Forager Lobster Mushroom Jamboree",
    city: "Itasca County, MN",
    date: new Date("2017/08/19"),
    imageSrc: "./img/shows/gentleman-forager.jpg",
    imageAlt: "Gentleman Forager Lobster Mushroom Jamboree",
    description: "<a href='https://www.gentlemanforager.com/product-page/2017-lobster-mushroom-jamboree'>More info here!</a>",
  },
  {
    venue: "Icehouse—Don’t Leave Flowers CD Release",
    city: "Minneapolis",
    date: new Date("2017/09/01"),
    imageSrc: "./img/shows/icehouse.png",
    imageAlt: "Icehouse",
    description: "It's our release party for Don't Leave Flowers!<br />"+
                  "<a href='https://www.icehousempls.com/events/2017/9/1/ginstrings-cd-release-dont-leave-flowers-w-special-guest' target='_blank'>Grab yer tickets here.</a>",
  },
  {
    venue: "Lift Bridge Brewery",
    city: "Stillwater, MN",
    date: new Date("2017/09/09"),
    imageSrc: "./img/shows/liftbridge.png",
    imageAlt: "Lift Bridge",
    // description: ""
  },
  {
    venue: "Fresh Grass Music Festival",
    city: "North Adams, MA",
    date: new Date("2017/09/15"),
    endDate: new Date("2017/09/17"),
    imageSrc: "./img/shows/fresh-grass.png",
    imageAlt: "Fresh Grass Music Festival",
    description: "We are performing in the band competition—<a href='http://freshgrass.com/2017-music-schedule/'>more details to come!</a>",
  },
  {
    venue: "Iowa City Yacht Club",
    city: "Iowa City",
    date: new Date("2017/09/21"),
    imageSrc: "./img/shows/iowa-yacht-club.png",
    imageAlt: "Iowa City Yacht Club",
    // description: "",
  },
  {
    venue: "Westport Saloon",
    city: "Kansas City, MO",
    date: new Date("2017/09/22"),
    imageSrc: "./img/shows/westport-saloon.png",
    imageAlt: "Westport Saloon",
    // description: "",
  },
  {
    venue: "Pickin on the Curtois",
    city: "Steelville, MO",
    date: new Date("2017/09/23"),
    imageSrc: "./img/shows/pickin-curtois.jpg",
    imageAlt: "Pickin on the Curtois",
    // description: "",
  },
  {
    venue: "Point Labaddie Brewery",
    city: "Labadie, MO",
    date: new Date("2017/09/24"),
    imageSrc: "./img/shows/labaddie.jpeg",
    imageAlt: "Labaddie Brewery",
    // description: "",
  },
  {
    venue: "Short Branch Saloon",
    city: "Neenah, WI",
    date: new Date("2017/10/20"),
    imageSrc: "./img/shows/shortbranch.jpg",
    imageAlt: "Short Branch Saloon",
    // description: "",
  },
  {
    venue: "Fernson and 5th",
    city: "Sioux Falls, SD",
    date: new Date("2017/10/27"),
    imageSrc: "./img/shows/fernson.jpeg",
    imageAlt: "Fernson and 5th",
    description: "Guess what! It's a Halloween costume party.",
  },
  {
    venue: "Dempsey's Pub",
    city: "Fargo, ND",
    date: new Date("2017/10/28"),
    imageSrc: "./img/shows/dempseys.png",
    imageAlt: "Dempsey's Pub",
    description: "Our second night in a row of a Halloween costume party!",
  },
  {
    venue: "Malarkey's Pub",
    city: "Wasau, WI",
    date: new Date("2017/12/14"),
    imageSrc: "./img/shows/malarkeys.png",
    imageAlt: "Malarkey's Pub",
    description: "Join us for Surly's Winter beer release!",
  },
  {
    venue: "Cranky Pat's",
    city: "Neenah, WI",
    date: new Date("2017/12/15"),
    imageSrc: "./img/shows/cranky-pats.jpg",
    imageAlt: "Cranky Pat's",
    description: "With special guest 2nd Strings",
  },
  {
    venue: "Zebra Lounge",
    city: "Bozeman, MT",
    date: new Date("2018/1/18"),
    imageSrc: "./img/shows/zebra.jpg",
    imageAlt: "Zebra Lounge",
    description: "",
  },
  {
    venue: "Great Northern Bar",
    city: "Whitefish, MT",
    date: new Date("2018/1/19"),
    imageSrc: "./img/shows/greatnorthern.jpg",
    imageAlt: "Great Northern Bar",
    description: "",
  },
  {
    venue: "Nola's Lounge",
    city: "Minot, ND",
    date: new Date("2018/1/20"),
    imageSrc: "./img/shows/nolas.jpeg",
    imageAlt: "Nola's Lounge",
    description: "",
  },
  {
    venue: "Lakeview Uncommon Ground",
    city: "Chicago, IL",
    date: new Date("2018/1/26"),
    imageSrc: "./img/shows/uncommon-ground.png",
    imageAlt: "Uncommon Ground",
    description: "<a href='http://www.uncommongroundcalendar.com/blog/event/ginstrings-w-the-squarshers/'>Grab some tickets!</a> We're playing with <em>The Squarshers</em>",
  },
  {
    venue: "Red Herring Lounge",
    city: "Duluth, MN",
    date: new Date("2018/2/8"),
    imageSrc: "./img/shows/red-herring.png",
    imageAlt: "Red Herring Lounge",
    description: "Playing with Zach Deputy. <a href='https://www.ticketfly.com/purchase/event/1605798?utm_medium=ampOfficialEvent&utm_source=ginstringsWebsite'>Get some tickets here</a>!",
  },
  {
    venue: "Top Hat Theater",
    city: "Ulen, MN",
    date: new Date("2018/2/10"),
    imageSrc: "./img/shows/top-hat-theater.png",
    imageAlt: "Top Hat Theater",
    description: "Get your tickets <a href='https://www.thetophattheatre.com/tickets/'>here</a>!",
  },
  {
    venue: "Guu's on Main",
    city: "Stevens Point, WI",
    date: new Date("2018/2/22"),
    imageSrc: "./img/shows/guus.png",
    imageAlt: "Guu's on Main",
    description: "With special guest <a href='https://www.facebook.com/SoulSymmetryBand/'>Soul Symmetry</a>",
  },
  {
    venue: "Minocqua Brewery",
    city: "Minocqua, WI",
    date: new Date("2018/2/23"),
    imageSrc: "./img/shows/minocqua.png",
    imageAlt: "Minocqua Brewery",
    description: "",
  },
  {
    venue: "Short Branch Saloon",
    city: "Neenah, WI",
    date: new Date("2018/2/24"),
    imageSrc: "./img/shows/shortbranch.jpg",
    imageAlt: "Short Branch Saloon",
    description: "",
  },
  {
    venue: "Gasoline",
    city: "Green Bay, WI",
    date: new Date("2018/2/25"),
    imageSrc: "./img/shows/gasoline.jpg",
    imageAlt: "Gasoline",
    description: "",
  },
  {
    venue: "Ky's Basement",
    city: "St Louis, MO",
    date: new Date("2018/3/16"),
    imageSrc: "./img/green-logo-dark.jpg",
    imageAlt: "Ky's Basement",
    description: "<a href='https://www.facebook.com/events/155109651814481/'>More info here!</a>",
  },
  {
    venue: "Broadway Oyster Bar",
    city: "St Louis, MO",
    date: new Date("2018/3/17"),
    imageSrc: "./img/shows/broadway-oyster.png",
    imageAlt: "Broadway Oyster Bar",
    description: "Playing with ClusterPluck at a St. Paddy's day party! <a href='http://www.broadwayoysterbar.com/musicsched.html'>Check out Broadway Oyster Bar's website</a> for more info.",
  },
  {
    venue: "Point Labaddie Brewery",
    city: "Labadie, MO",
    date: new Date("2018/3/18"),
    imageSrc: "./img/shows/labaddie.jpeg",
    imageAlt: "Point Labaddie Brewery",
    description: "",
  },
  {
    venue: "Dempsey's",
    city: "Fargo, ND",
    date: new Date("2018/3/24"),
    imageSrc: "./img/shows/dempseys.png",
    imageAlt: "Dempsey's",
    description: "",
  },
  {
    venue: "Gunflint Tavern",
    city: "Grand Marais, MN",
    date: new Date("2018/4/6"),
    imageSrc: "./img/shows/gunflint.jpg",
    imageAlt: "Gunflint Tavern",
    description: "",
  },
  {
    venue: "Mountain Meltdown",
    city: "Lutsen, MN",
    date: new Date("2018/4/7"),
    imageSrc: "./img/shows/mt-meltdown.jpg",
    imageAlt: "Mountain Meltdown",
    description: "",
  },
]